"""updated the models to support the ticketing and urls for both the posters and for the QR

Revision ID: 8d3ff67ba518
Revises: 726d4cce1cfd
Create Date: 2026-01-14 10:54:44.223271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3ff67ba518'
down_revision = '726d4cce1cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_sold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sale_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sale_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('quantity_total',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('qr_image_url', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'ticket_types', ['ticket_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('qr_image_url')
        batch_op.drop_column('ticket_type_id')

    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.alter_column('quantity_total',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('access_level')
        batch_op.drop_column('sale_end')
        batch_op.drop_column('sale_start')
        batch_op.drop_column('quantity_sold')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
